openapi: 3.0.3
info:
  title: FairGig Certificate Service API
  version: 1.0.0
paths:
  /certificate/build:
    get:
      summary: Build certificate
      responses:
        "200":
          description: OK
